apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-project-app
  labels:
    app.kubernetes.io/name: first-project-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: first-project-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: first-project-app
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

